"""Export single-branch GDN-2 weights to C header (v3, current pipeline).

Trains the single-branch model (readout="last") with per-window z-score
targets on CALCE (the current protocol), then exports all tensors to
gdn_weights.h + test input/reference for the C verification chain.
"""
import argparse
import sys
from pathlib import Path
import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).parent))
from gdn_model import build_gdn_model, masked_mae
from make_figures import load_series

DEV = torch.device("cuda" if torch.cuda.is_available() else "cpu")
W, BATCH, EPOCHS, SEED = 64, 64, 100, 42
EPS = 1e-6


def _emit_floats(f, values) -> None:
    """Write floats eight per line, each with an `f` suffix."""
    for i, v in enumerate(values):
        f.write(f" {v}f," if i % 8 else f"\n    {v}f,")
    f.write("\n")


def _emit_int8(f, values, per_line: int = 16) -> None:
    for i, v in enumerate(values):
        f.write(f" {v}," if i % per_line else f"\n    {v},")
    f.write("\n")


def write_array(f, name, arr, quant: str = "fp32") -> None:
    """Emit one tensor as C arrays.

    2-D weights follow PyTorch's dynamic-quantization convention: in int8
    mode the matrix is stored as signed bytes plus one fp32 scale per
    output channel (symmetric, s_i = max_j|W_ij| / 127). 1-D tensors
    (biases, RMSNorm weights, A_log, dt) stay fp32 in both modes -- they
    amount to a few KB, and PyTorch keeps biases fp32 as well.
    """
    arr = np.asarray(arr, dtype=np.float32)
    if arr.ndim == 3:  # depthwise conv weight (C,1,K) -> (C,K)
        arr = arr.squeeze(1)
    if arr.ndim == 1:
        f.write(f"#define {name}_size {len(arr)}\n")
        f.write(f"const float {name}[{len(arr)}] = {{")
        _emit_floats(f, [f"{v:.7f}" for v in arr])
        f.write("};\n\n")
        return

    rows, cols = arr.shape
    f.write(f"#define {name}_rows {rows}\n")
    f.write(f"#define {name}_cols {cols}\n")
    if quant in ("int8", "int4"):
        qmax = 127 if quant == "int8" else 7
        scale = np.abs(arr).max(axis=1) / float(qmax)
        scale = np.where(scale == 0.0, 1.0, scale)  # all-zero row guard
        q = np.clip(np.round(arr / scale[:, None]), -qmax, qmax).astype(np.int32)
        f.write(f"const float {name}_s[{rows}] = {{")
        _emit_floats(f, [f"{v:.9g}" for v in scale])
        f.write("};\n")
        if quant == "int8":
            q8 = q.astype(np.int8)
            f.write(f"const signed char {name}_q[{rows * cols}] = {{")
            _emit_int8(f, q8.flatten().tolist())
        else:
            # two signed nibbles per byte, low nibble first; a row-major pair
            # may straddle the row boundary, which the C reader handles by
            # indexing the flat array the same way
            flat = q.flatten()
            if flat.size % 2:
                flat = np.append(flat, 0)
            packed = ((flat[0::2] & 0xF) | ((flat[1::2] & 0xF) << 4))
            f.write(f"const unsigned char {name}_q4[{packed.size}] = {{")
            _emit_int8(f, packed.astype(np.uint8).tolist())
        f.write("};\n\n")
        return

    f.write(f"const float {name}[{rows * cols}] = {{")
    _emit_floats(f, [f"{v:.7f}" for v in arr.flatten()])
    f.write("};\n\n")


def write_header(out_path, state, quant: str, banner: str) -> int:
    """Write every tensor in `state` to `out_path`; returns the array count."""
    with open(out_path, "w") as f:
        f.write("// Auto-generated GDN-2 weights for MCU deployment (v3)\n")
        f.write(f"// {banner}\n")
        f.write(f"// quantization: {quant}\n")
        f.write("#ifndef GDN_WEIGHTS_H\n#define GDN_WEIGHTS_H\n\n")
        for name, tensor in sorted(state.items()):
            write_array(f, name.replace(".", "_"), tensor.numpy(), quant)
        f.write("#endif // GDN_WEIGHTS_H\n")
    return len(state)


def emit_c_init(out_path, state) -> None:
    """Emit ms_init.h, which fills a GDN2MS_Variables from the header.

    Written out rather than hand-maintained: the multi-scale model has 122
    tensors, and a single mistyped field would silently become a NULL weight
    pointer at run time.
    """
    def n(key):
        return key.replace(".", "_")

    out = ["/* Auto-generated by export_gdn_weights.py --emit-init.",
           " * Fills GDN2MS_Variables from the arrays in gdn_ms_weights.h. */",
           "#pragma once",
           '#include "gdn2_multiscale.c"',
           "",
           "static void ms_init(GDN2MS_Variables *m) {",
           "    *m = (GDN2MS_Variables){0};",
           "    m->d_model = 64; m->num_heads = 4; m->head_dim = 16;",
           "    m->head_vdim = 32; m->window_size = 64; m->conv_size = 4;"]
    for i in range(3):
        ps = int(state[f"branches.{i}.proj.weight"].shape[1])
        out.append(f"    m->br[{i}].patch_size = {ps};")
        out.append(f"    m->br[{i}].tokens = 64 / {ps};")
        out.append(f"    m->br[{i}].proj_w = GDN_MAT({n(f'branches.{i}.proj.weight')});")
        out.append(f"    m->br[{i}].proj_b = {n(f'branches.{i}.proj.bias')};")
        for j in range(2):
            p = f"branches.{i}.layers.{j}"
            for field, key in (
                    ("q_w", "gdn.q_proj.weight"), ("q_c", "gdn.q_conv.conv.weight"),
                    ("k_w", "gdn.k_proj.weight"), ("k_c", "gdn.k_conv.conv.weight"),
                    ("v_w", "gdn.v_proj.weight"), ("v_c", "gdn.v_conv.conv.weight"),
                    ("out_w", "gdn.out_proj.weight"), ("f0_w", "gdn.f_proj.0.weight"),
                    ("f1_w", "gdn.f_proj.1.weight"), ("b_w", "gdn.b_proj.weight"),
                    ("w_w", "gdn.w_proj.weight"), ("g0_w", "gdn.g_proj.0.weight"),
                    ("g1_w", "gdn.g_proj.1.weight")):
                out.append(f"    m->br[{i}].layers[{j}].{field} = "
                           f"GDN_MAT({n(p + '.' + key)});")
            for field, key in (("A_log", "gdn.A_log"), ("dt", "gdn.dt_bias"),
                               ("onorm", "gdn.out_norm.weight"),
                               ("norm", "norm.weight")):
                out.append(f"    m->br[{i}].layers[{j}].{field} = "
                           f"{n(p + '.' + key)};")
    for j in range(2):
        for field, key in (("wq", "W_q.weight"), ("wk", "W_k.weight"),
                           ("wv", "W_v.weight")):
            out.append(f"    m->cross[{j}].{field} = "
                       f"GDN_MAT({n(f'cross_stage.{j}.{key}')});")
    for field, key in (("h1_w", "head_cap.0.weight"), ("h1_b", "head_cap.0.bias"),
                       ("h2_w", "head_cap.3.weight"), ("h2_b", "head_cap.3.bias")):
        if field.endswith("_w"):
            out.append(f"    m->{field} = GDN_MAT({n(key)});")
        else:
            out.append(f"    m->{field} = {n(key)};")
    out.append("}")
    Path(out_path).write_text("\n".join(out) + "\n")
    print(f"wrote {out_path} ({len(out)} lines)", flush=True)


def build_model(arch: str, window: int):
    """Rebuild the architecture a checkpoint belongs to."""
    if arch == "ms":
        return build_gdn_model(multiscale=True, stage_query=True, input_dim=1,
                               window_size=window, output_len=1,
                               readout="last")
    return build_gdn_model(multiscale=False, input_dim=1, window_size=window,
                           output_len=1, readout="last")


def window_from_ckpt(args, ck, state) -> None:
    """Emit the C test window and its PyTorch reference.

    The window is taken at the checkpoint's own starting point and
    normalised with the checkpoint's own lo/hi, so the C side and PyTorch
    see byte-identical inputs. Writing test_input.h here also retires the
    hand-maintained copy the harness used to depend on.
    """
    caps, _train_cells, test_cell, W, _sps, _eol = load_series(args.dataset)
    lo, hi = ck["lo"], ck["hi"]
    tc = (caps[test_cell] - lo) / (hi - lo + EPS)
    sp = int(ck.get("sp", W))
    win = tc[sp - W:sp]

    out_dir = Path(args.out).parent
    # The single-branch harness owns the unsuffixed names; anything else
    # writes beside them so neither overwrites the other's reference.
    tag = "" if args.arch == "single" else f"_{args.arch}"
    np.savetxt(out_dir / f"test_input{tag}.csv", win, fmt="%.8f")
    (out_dir / f"test_input{tag}.h").write_text(
        "#pragma once\n#define TEST_INPUT "
        + ", ".join(f"{v:.8f}f" for v in win) + "\n")

    model = build_model(args.arch, W)
    model.load_state_dict(state)
    model.eval()
    with torch.no_grad():
        pred = model(torch.tensor(win, dtype=torch.float32)
                     .view(1, W, 1)).item()
    (out_dir / f"test_py_out{tag}.txt").write_text(f"{pred:.10f}")
    print(f"test window: {args.dataset} {test_cell} cycles {sp - W}:{sp} "
          f"-> PyTorch {pred:.10f}", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None,
                    help="output header (default: gdn_weights.h for fp32, "
                         "gdn_weights_q8.h for int8, gdn_weights_q4.h for "
                         "int4)")
    ap.add_argument("--quant", choices=("fp32", "int8", "int4"),
                    default="fp32",
                    help="weight storage; the low-bit modes keep 1-D tensors "
                         "in fp32")
    ap.add_argument("--from-ckpt", default=None,
                    help="re-export from a saved checkpoint (skips training); "
                         "accepts a bare state_dict or a per-SP checkpoint "
                         "that wraps one under 'state_dict'")
    ap.add_argument("--arch", choices=("single", "ms"), default="single",
                    help="model family: single-branch, or the multiscale "
                         "stage-query model the paper reports")
    ap.add_argument("--dataset", default="calce",
                    help="used with --from-ckpt on a per-SP checkpoint to "
                         "rebuild that checkpoint's test window")
    ap.add_argument("--emit-init", default=None,
                    help="also write a C initialiser (ms_init.h) for the "
                         "multiscale harness")
    args = ap.parse_args()
    # Distinct defaults keep the committed fp32 header from being clobbered
    # by an int8 run (and vice versa).
    if args.out is None:
        args.out = f"gdn_weights{'' if args.quant == 'fp32' else '_q' + args.quant[-1]}.h"

    if args.from_ckpt:
        obj = torch.load(args.from_ckpt, map_location="cpu",
                         weights_only=False)
        # per-SP checkpoints wrap the weights alongside the protocol's
        # constants; a plain export is already a state_dict
        state = obj["state_dict"] if (isinstance(obj, dict)
                                      and "state_dict" in obj) else obj
        banner = ("multiscale stage-query, patch 2/4/8, d_model=64, 2 layers"
                  if args.arch == "ms"
                  else "single-branch, patch=2, d_model=64, 2 layers")
        n = write_header(args.out, state, args.quant, banner)
        print(f"re-exported {n} arrays to {args.out} ({args.quant})",
              flush=True)
        if isinstance(obj, dict) and {"lo", "hi", "W"} <= set(obj):
            window_from_ckpt(args, obj, state)
        if args.emit_init:
            emit_c_init(args.emit_init, state)
        return

    torch.manual_seed(SEED)
    np.random.seed(SEED)
    caps, train_cells, test_cell, W, sps, eol_ah = load_series("calce")
    all_tr = np.concatenate([caps[c] for c in train_cells])
    lo, hi = all_tr.min(), all_tr.max()

    model = build_gdn_model(multiscale=False, input_dim=1, window_size=W,
                            output_len=1, readout="last").to(DEV)
    opt = torch.optim.Adam(model.parameters(), lr=1e-3)

    X, Y = [], []
    for c in train_cells:
        seq = (caps[c] - lo) / (hi - lo + EPS)
        for i in range(W, len(seq)):
            X.append(seq[i - W:i, None])
            Y.append(seq[i])
    X = np.stack(X).astype(np.float32)
    Y = np.array(Y, dtype=np.float32)
    N = len(X)
    print(f"[train] single-branch z-score (N={N}) ...", flush=True)
    for ep in range(EPOCHS):
        model.train()
        perm = np.random.permutation(N)
        for s in range(0, N, BATCH):
            idx = perm[s:s + BATCH]
            x = torch.tensor(X[idx]).to(DEV)
            y = torch.tensor(Y[idx]).to(DEV)
            opt.zero_grad()
            pred = model(x).squeeze(-1)
            wmean = x[:, :, 0].mean(dim=1)
            wstd = x[:, :, 0].std(dim=1) + EPS
            tgt = (y - wmean) / wstd
            loss = masked_mae(pred, tgt, torch.ones_like(y))
            loss.backward()
            opt.step()
        if ep % 25 == 0:
            print(f"    ep{ep} loss={loss.item():.4f}", flush=True)

    state = model.cpu().state_dict()
    n = write_header(
        args.out, state, args.quant,
        f"single-branch, patch=2, d_model=64, 2 layers, "
        f"params={sum(p.numel() for p in model.parameters()):,}")
    print(f"exported to {args.out}: {n} weight arrays ({args.quant})",
          flush=True)

    # checkpoint for verification
    ckpt = Path(args.out).with_suffix(".pt")
    torch.save(state, ckpt)
    print(f"saved checkpoint: {ckpt}", flush=True)

    # test input + PyTorch reference (raw model output, z-space)
    tc = (caps[test_cell] - lo) / (hi - lo + EPS)
    np.savetxt(Path(args.out).parent / "test_input.csv", tc[0:W], fmt="%.8f")
    model.eval()
    with torch.no_grad():
        cin = torch.tensor(tc[0:W], dtype=torch.float32).unsqueeze(0).unsqueeze(-1)
        pred = model(cin).item()
    (Path(args.out).parent / "test_py_out.txt").write_text(f"{pred:.10f}")
    print(f"test: PyTorch pred on window[0:64]={pred:.10f}", flush=True)


if __name__ == "__main__":
    main()
